allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - '@tauri-apps/plugin-log@2.9.0'
  - '@typescript-eslint/eslint-plugin@8.64.0'
  - '@typescript-eslint/parser@8.64.0'
  - '@typescript-eslint/project-service@8.64.0'
  - '@typescript-eslint/scope-manager@8.64.0'
  - '@typescript-eslint/tsconfig-utils@8.64.0'
  - '@typescript-eslint/type-utils@8.64.0'
  - '@typescript-eslint/types@8.64.0'
  - '@typescript-eslint/typescript-estree@8.64.0'
  - '@typescript-eslint/utils@8.64.0'
  - '@typescript-eslint/visitor-keys@8.64.0'
  - antd@6.5.1
onlyBuiltDependencies:
  - esbuild
