export const OPERATION_KEYS = {
  instance: (instanceId: string) => `instance:${instanceId}`,
  createInstance: 'create-instance',
  deleteInstance: 'delete',

  installVersion: (tag: string) => `install:${tag}`,
  uninstallVersion: (version: string) => `uninstall:${version}`,
  installComponent: (componentId: string) => `install-component:${componentId}`,
  reinstallComponent: (componentId: string) => `reinstall-component:${componentId}`,
  uninstallComponent: (componentId: string) => `uninstall-component:${componentId}`,
  fetchReleases: 'fetch-releases',

  backupCreate: 'backup:create',
  backupRestore: 'backup:restore',
  backupDelete: 'backup:delete',

  advancedSaveGithubProxy: 'adv:save-github-proxy',
  advancedSaveProxy: 'adv:save-proxy',
  advancedSavePypiMirror: 'adv:save-pypi-mirror',
  advancedSaveNodejsMirror: 'adv:save-nodejs-mirror',
  advancedSaveNpmRegistry: 'adv:save-npm-registry',
  advancedSaveCloseToTray: 'adv:save-close-to-tray',
  advancedSaveAutostartMinimizeToTray: 'adv:save-autostart-minimize-to-tray',
  advancedSaveCheckInstanceUpdate: 'adv:save-check-instance-update',
  advancedSavePersistInstanceState: 'adv:save-persist-instance-state',
  advancedSaveIgnoreExternalPath: 'adv:save-ignore-external-path',
  advancedSaveMainlandAcceleration: 'adv:save-mainland-acceleration',
  advancedSaveAutostart: 'adv:save-autostart',
  advancedSaveUseUvForDeps: 'adv:save-use-uv-for-deps',
  advancedSaveLockCheckExtensionWhitelist: 'adv:save-lock-check-extension-whitelist',
  advancedSaveThemePreference: 'adv:save-theme-preference',
  advancedClearData: (instanceId: string) => `adv:data-${instanceId}`,
  advancedClearVenv: (instanceId: string) => `adv:venv-${instanceId}`,
  advancedClearPycache: (instanceId: string) => `adv:pycache-${instanceId}`,
  advancedRepairInstance: (instanceId: string) => `adv:repair-${instanceId}`,
  advancedRebuildInstanceManifest: 'adv:rebuild-instance-manifest',
} as const;
